
package test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestServiceImpl", targetNamespace = "http://webservicetest.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hiWebService", targetNamespace = "http://webservicetest.example.com/", className = "test.HiWebService")
    @ResponseWrapper(localName = "hiWebServiceResponse", targetNamespace = "http://webservicetest.example.com/", className = "test.HiWebServiceResponse")
    @Action(input = "http://webservicetest.example.com/TestServiceImpl/hiWebServiceRequest", output = "http://webservicetest.example.com/TestServiceImpl/hiWebServiceResponse")
    public String hiWebService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
